bash -c 'sudo pacman -S alacritty xterm dmenu picom xf86-input-libinput xmonad xmonad-contrib htop ncdu vim nano xorg-xprop flameshot pulseaudio-alsa pulseaudio-bluetooth pamixer tlp youtube-dl nitrogen chromium krita xdotool gimp mpv vlc audacity discord libreoffice-still'
bash -c 'yay -S tlpui-git spotify github-desktop-bin nerd-fonts-complete ttf-iosevka ttc-iosevka-aile mirage libinput-gestures sublime-text-4'
bash -c 'mkdir ~/.xmonad && cp xmonad.hs ~/.xmonad/'
bash -c 'mkdir ~/.xmobarrc && cp xmobar ~/.xmobarrc/'
bash -c 'mkdir -p ~/.config/alacritty && cp config/alacritty.yml ~/.config/alacritty/'
bash -c 'mkdir -p ~/.config/xmonad/scripts && cp config/help ~/.config/xmonad/'
bash -c 'cp config/shell/help.sh config/shell/startup_screen.sh ~/.config/xmonad/scripts/'
