bash -c 'pacman -S alacritty xmonad xmonad-contrib htop ncdu yay subl vim nano xorg-xprop flameshot pulseaudio-alsa pulseaudio-bluetooth pamixer tlp youtube-dl nitrogen chromium krita gimp mpv vlc audacity mirage discord'
bash -c 'yay -S tlpui-git spotify github-desktop-bin nerd-fonts-complete ttf-iosevka ttc-iosevka-aile'
bash -c 'mkdir ~/.xmonad && cp xmonad.hs ~/.xmonad/'
bash -c 'mkdir ~/.xmobarrc && cp xmobar ~/.xmobarrc/'
bash -c 'mkdir -p ~/.config/alacritty &&'
bash -c 'mkdir -p ~/.config/xmonad/scripts && cp config/help ~/.config/xmonad/'
bash -c 'cp config/shell/help.sh config/shell/startup_screen.sh ~/.config/xmonad/scripts/'
